- name: install logstash
  package: name="{{item}}"
  with_items:
  - "logstash"
  - "java-devel"
  notify:
    - start logstash

- name: Try and find the rubydebug plugin
  find:
    paths: /usr/share/logstash
    recurse: yes
    patterns: "rubydebug*"
  register: rubydebug_plugin_installed

- name: install the ruby debug plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-codec-rubydebug
  when: rubydebug_plugin_installed.files | default ([]) | length ==0

- name: Try and find the collectd plugin
  find:
    paths: /usr/share/logstash
    recurse: yes
    patterns: "collectd*"
  register: collectd_plugin_installed

- name: install the collectd plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-codec-collectd
  when: collectd_plugin_installed.files | default ([]) | length ==0

- name: Try and find the mutate plugin
  find:
    paths: /usr/share/logstash
    recurse: yes
    patterns: "mutate*"
  register: mutate_plugin_installed

- name: Install the mutate plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-filter-mutate
  when: mutate_plugin_installed.files | default ([]) | length ==0


- name: create logstash.yml
  template: dest="/etc/logstash/logstash.yml" mode=644 src=logstash.yml
  notify:
    - start logstash

- name: create conf.d directory
  file: path="/etc/logstash/conf.d" state="directory"

- name: create logstash filebeat config
  template: dest="/etc/logstash/conf.d/logstash-filebeats.conf" mode=644 src=logstash-filebeats.conf
  notify:
    - start logstash

- name: create logstash metricbeat config
  template: dest="/etc/logstash/conf.d/logstash-metrics.conf" mode=644 src=logstash-metrics.conf
  notify:
    - start logstash

- lineinfile:
    path: /etc/logstash/log4j2.properties
    regexp: '^appender.rolling.policies.time.interval ='
    line: 'appender.rolling.policies.time.interval = 10'
  notify:
    - start logstash

- name: logrotate
  template: dest="/etc/logrotate.d/logstash" owner=root group=root mode=644 src=logrotate.j2
