- user:
    name: kibana
    shell: /sbin/nologin

- name: install kibana
  package: name="{{item}}"
  with_items:
  - "kibana"
  notify:
    - restart kibana

- file:
    path: /usr/share/kibana/
    owner: kibana
    group: kibana
    recurse: yes

- lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^server.port:"
    line: "server.port: 5601"
  notify:
    - restart kibana

- lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^server.host:"
    line: "server.host: {{facter_ipaddress_eth1}}"
  notify:
    - restart kibana

- lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^elasticsearch.url:"
    line: 'elasticsearch.url: "http://{{facter_ipaddress_eth1}}:9200"'
  notify:
    - restart kibana

# - lineinfile:
#     path: /etc/elasticsearch/elasticsearch.yml
#     regexp: "^discovery.zen.ping.unicast.hosts:"
#     line: 'discovery.zen.ping.unicast.hosts: ["192.168.33.10","192.168.33.11","192.168.33.12"]'
#   notify:
#     - restart elasticsearch
