---
- name: setup group
  group: name={{kafka_group}} system=yes

- name: Setup user
  user: name={{kafka_user}} system=yes group={{kafka_group}}

- name: Uncompress the kafka tar
  unarchive: copy=no creates=/opt/kafka_2.9.2-{{kafka_version}} dest=/opt src="{{ kafka_tarball_location }}/{{ kafka_tarball_name }}"

- name: Link /opt/kafka to the right version
  file: path="{{kafka_install_dir}}" state=link src=/opt/kafka_2.12-{{kafka_version}}

- name: Overwrite the start script so the Java Opts can be changed if Kafka 0.8.1.1
  lineinfile: dest=/opt/kafka_2.9.2-{{kafka_version}}/bin/kafka-server-start.sh regexp="^export KAFKA_HEAP_OPTS=" line="export KAFKA_HEAP_OPTS=\"{{ kafka_heap_opts }}\""
  notify:
    - restart kafka
  when: kafka_version == "0.8.1.1"

- name: Create data_dir
  file: path={{kafka_data_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: Remove lost+found in the datadir
  file: path="{{kafka_data_dir}}/lost+found" state=absent

- name: Create log_dir
  file: path={{kafka_log_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: link log_dir to /opt/kafka/logs
  file: path=/opt/kafka/logs state=link src={{kafka_log_dir}}

- name: link conf_dir to /opt/kafka/config
  file: path={{kafka_conf_dir}} state=link src=/opt/kafka/config

# Setup log4j.properties
- name: create log4j.properties
  template: dest="{{kafka_conf_dir}}/log4j.properties" owner={{kafka_user}} group={{kafka_group}} mode=644 src=log4j.properties.j2
  notify:
    - restart kafka

- name: logrotate
  template: dest="/etc/logrotate.d/kafka" owner=root group=root mode=655 src=logrotate.j2

- name: Remove log
  shell: "/sbin/logrotate -f /etc/logrotate.d/kafka"

# Setup server.properties
# - name: create server.properties
#   template: dest="{{kafka_conf_dir}}/server.properties" owner={{kafka_user}} group={{kafka_group}} mode=640 src=server.properties.j2
#   notify:
#     - restart kafka

- name: lookup brokerid
  shell: "cat {{kafka_conf_dir}}/server.properties | grep broker.id | cut -c 11-"
  register: brokerid_out

- set_fact:
    broker_id: "{{brokerid_out.stdout}}"

- name: Put jolokia jar in place
  copy: dest="{{kafka_install_dir}}/bin/jolokia-jvm-1.3.5-agent.jar" src=jolokia-jvm-1.3.5-agent.jar
  notify:
    - restart kafka

- name: create systemd config
  template: dest={{kafka_systemd_service}} owner=root group=root mode=644 src=kafka.service.j2
  notify:
    - restart kafka

- command: systemctl daemon-reload

- meta: flush_handlers
