---
- include: stop.yml
  when: run_mode == 'Stop'

- include: install.yml
  when: not skip_install and ( run_mode == 'Install' or run_mode == 'Deploy' )

- include: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- include: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'

- shell: /opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181/kafka --topic filebeats --partitions 3 --replication-factor 3 --if-not-exists
- shell: /opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181/kafka --topic metricbeats --partitions 3 --replication-factor 3 --if-not-exists
