---
apache_mirror: http://apache.mirrors.tds.net
#kafka_hosts: "{{ansible_fqdn}}:9092"
kafka_hosts: "{{ groups ['kafka_hosts'] | join(',') }}"
zookeeper_hosts: server1:2181,server2:2181,server3:2181/kafka
kafka_version: 0.10.2.1
run_mode: Deploy
skip_install: False

#kafka_listen_address: "{{ansible_hostname}}"
kafka_num_network_threads: 2
kafka_num_io_threads: 2
kafka_num_partitions: 2
kafka_port: 9092
kafka_socket_send_buffer_bytes: 1048576
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_request_max_bytes: 104857600
kafka_log_flush_interval_messages: 10000
kafka_log_flush_interval_ms: 1000
kafka_log_retention_bytes: 104857600  #100 M
kafka_log_retention_hours: 24
kafka_log_segment_bytes: "{{kafka_log_retention_bytes}}"
kafka_log_cleanup_interval_mins: 1
kafka_heap_opts: "-Xmx512M -javaagent:jolokia-jvm-1.3.5-agent.jar=port=7720,host=localhost"
kafka_tarball_location: /root
kafka_tarball_name: "kafka_2.12-{{kafka_version}}.tgz"
monasca_wait_for_period: 30
monasca_log_level: WARN
zookeeper_connection_timeout_ms: 1000000

verify: True
kafka_install_dir: /opt/kafka

kafka_conf_dir: /etc/kafka
kafka_data_dir: /var/kafka
kafka_group: kafka
kafka_user: kafka
kafka_log_dir: /var/log/kafka
kafka_upstart_conf: /etc/init/kafka.conf
kafka_systemd_service: /etc/systemd/system/kafka.service
kafka_auto_create_topics: "false"
