version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        ports:
            - 2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        ports:
            - 2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        ports:
            - 2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    kafka:
      image: wurstmeister/kafka
      ports:
        - 9092
      environment:
        KAFKA_CREATE_TOPICS: "beats:3:3,metricbeat:3:3,httpbeats:3:3"
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
        KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
        KAFKA_ADVERTISED_HOST_NAME: 192.168.33.11
        KAFKA_ADVERTISED_PORT: 9092
