- name: install metricbeat
  package: name="{{item}}"
  with_items:
  - "metricbeat"
  notify:
    - start metricbeat

- name: create metricbeat.yml
  template: dest="/etc/metricbeat/metricbeat.yml" mode=644 src=metricbeat.yml.j2
  notify:
    - start metricbeat

- name: create conf.d directory
  file: path="/etc/filebeat/conf.d" state="directory"
